title: Eli Wang # your name (or website title) here
logo: "my-photo-2.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | ex-Tesla | ex-Meta/USC
  <br><br>
  3 years of experience in end-to-end data analysis, workflow automation, and machine learning (speacialized in NLP).
  Previously on Tesla's Analytics team and supported decision-making for multiple cross-functional teams & leaders across North America.
  <br><br>
  <a href="https://www.linkedin.com/in/eliwangjq">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
